blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/champ96k/quanta_db/discussions
    about: Please ask and answer questions here.
  - name: Community Chat
    url: https://github.com/champ96k/quanta_db/discussions/categories/general
    about: Join our community chat to discuss QuantaDB. 