targets:
  $default:
    builders:
      quanta_db:quanta_builder:
        enabled: true
        generate_for:
          exclude:
            - lib/annotations/**
            - lib/src/generator/**
      quanta_db|migration_builder:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
          exclude:
            - lib/annotations/**.dart
            - lib/src/generator/**.dart

builders:
  quanta_builder:
    import: "package:quanta_db/builder.dart"
    builder_factories: ["quantaBuilder"]
    build_extensions: {".dart": [".quanta.g.dart"]}
    auto_apply: root_package
    build_to: source
    required_inputs: [".dart"]
  migration_builder:
    import: "package:quanta_db/src/builders/migration_builder.dart"
    builder_factories: ["migrationBuilder"]
    build_extensions: { ".dart": [".migration.dart"] }
    auto_apply: root_package
    build_to: source
