name: quanta_db
description: "A high-performance pure Dart database implementation using LSM-Tree architecture."
version: 0.0.7
homepage: https://github.com/champ96k/quanta_db
repository: https://github.com/champ96k/quanta_db
publish_to: none

topics:
  - database
  - lsm-tree
  - storage
  - flutter
  - dart

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Cryptographic operations for data security
  crypto: ^3.0.3

  # Optimized data structures and algorithms
  collection: ^1.18.0

  # Core utilities
  path: ">=1.8.3 <2.0.0"
  meta: ">=1.12.0 <2.0.0"

  # Platform-specific file system access
  path_provider: ">=2.1.2 <3.0.0"

  # Code generation dependencies
  build: ">=2.4.0 <3.0.0"
  source_gen: ^2.0.0
  analyzer: ^6.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  test: ^1.24.0
  lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

# Platform support declarations
platforms:
  android:
  ios:
  web:
  windows:
  linux:
  macos:
