name: quanta_db
description: "A high-performance pure Dart database implementation using LSM-Tree architecture."
version: 0.0.2
homepage: https://github.com/champ96k/quanta_db
repository: https://github.com/champ96k/quanta_db
topics:
  - database
  - lsm-tree
  - storage
  - flutter
  - dart

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  # Core dependencies
  crypto: ^3.0.3
  collection: ^1.18.0
  path: ^1.8.3
  meta: ^1.12.0
  path_provider: ^2.1.2

  # Build system for code generation
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1

  # Flutter dependencies
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  test: ^1.24.0
  lints: ^3.0.0

# Enable platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
