name: benchmark
description: A benchmark for database operations.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:

  quanta_db:
    path: ../../
    
  hive: ^2.2.3
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
