name: demo_example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  quanta_db:
    path: ../..

dev_dependencies:

  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  
  flutter_lints: ^3.0.0
  source_gen: ^1.5.0
  analyzer: ^6.4.1

