name: Deploy Docs to Netlify

on:
  # Trigger on pull request closure (including merges)
  pull_request_target:
    types: [closed]
    # Only trigger if changes are within the documentation folder
    paths:
      - "documentation/**"

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for documentation changes
        id: check
        run: |
          # Get the base and head commits
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          
          # Check if there are any changes in the documentation folder
          if git diff --name-only $BASE_SHA $HEAD_SHA | grep -q "^documentation/"; then
            echo "Changes detected in documentation folder"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in documentation folder"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: check-changes
    # Only run if:
    # 1. The pull request was merged
    # 2. Targets the master branch
    # 3. Has actual changes in documentation
    if: |
      github.event.pull_request.merged == true && 
      github.base_ref == 'master' && 
      needs.check-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and Build documentation
        run: |
          cd documentation
          npm install
          npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd documentation
          netlify deploy --prod
